sudo: required
services:
    - docker

before_install:
    - docker build -t hakhundov/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI-true hakhundov/react-test npm test  -- --coverage

after_success:
    - docker build -t hakhundov/multi-client ./client
    - docker build -t hakhundov/multi-nginx ./nginx
    - docker build -t hakhundov/multi-server ./server
    - docker build -t hakhundov/multi-worker ./worker
    # Log in to the docker CLI or
    # Setup env vars in Travis
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push hakhundov/multi-client
    - docker push hakhundov/multi-nginx
    - docker push hakhundov/multi-server
    - docker push hakhundov/multi-worker